import pandas as pd
d={'a':1,'b':2}
a=pd.Series(d)
b=pd.Series('imran',index=[1,2,3,4])
print(a)
print(b)
print()
print('index ',b.index)
print('values ',b.values)
print('get type for series using dtype')
print(a.dtype)
print(a.dtype)
print('get item type for series using itemsize')
print(a.size)
print(b.size)
print()
c=pd.Series()
print(c)
print(c.size)
print(c.empty)
print('return dimension')
print(a.ndim)
print(b.ndim)
print(c.ndim)
print('nan value ')
lst2=["imran",None,'irfan']
d=pd.Series(lst2)
print(d)
print(d.hasnans)
print('shape means return length')
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

print()
print(a.empty,b.empty,c.empty)   
print(a.hasnans,b.hasnans,c.hasnans)   
print(len(a),len(b))   
print(a.count( ),b.count( ))  